### PR TITLE
Allow users to stay on a specific release.

### PR DESCRIPTION
**Pull request by alphacc**
Operator don't necessary want to move to next version.

### CODE REVIEW

**Comment by apevec** [comment]
Good point, this will allow multiple release streams per OS version.

**Comment by alphacc** [comment]
That would be awesome to fix kilo before we release liberty to avoid issues.

**Comment by alphacc** [comment]
@apevec what do you mean ?

**Comment by alphacc** [comment]
@apevec : yeah we can use something else than 1.0.

**Comment by apevec** [comment]
Version is normally upstream version, and here there isn't any, esp. not semver one :)
So I'll change to Version: 1 and we'll keep bumping Release: only.

**Comment by apevec** [comment]
This will need followup with Epoch otherwise upgrades won't work for users who have centos-release-openstack already installed:

$ rpmdev-vercmp centos-release-openstack-kilo-1-2.el7  centos-release-openstack-kilo-2.el7
centos-release-openstack-kilo-1-2.el7 < centos-release-openstack-kilo-2.el7

**Comment by alphacc** [comment]
Can't we just obsolete centos-release-openstack ?

**Comment by apevec** [comment]
ok,  I'll try Obsoletes and push follow.

**Pull request merged**
