### PR TITLE
RDO branding

### PR DESCRIPTION
**Pull request by apevec**
Rename release RPM and repo file to keep RDO branding inside
CentOS CloudSIG.
Also instead of centos-release use system-release so RDO release RPM
can be installed on any EL variant.

@hguemar @alphacc @kbsingh This showed today up as GA blocker, please review from SIG side
and @markmc @pmyers from RDO side.

### CODE REVIEW

**Comment by apevec** [comment]
CBS scratch build for testing http://cbs.centos.org/koji/taskinfo?taskID=50962

**Comment by apevec** [comment]
Scratch build for testing http://cbs.centos.org/koji/taskinfo?taskID=50965

**Comment by alphacc** [comment]
As we did for SCL we could add : 

Requires: system-release

Otherwise it sounds good.

## 

Thomas.

**Comment by kbsingh** [comment]
I am not sure about this - where is the larger conversation taking place around this ? 

Key things to note here is that the payload we ship is still branded RDO, but is in effect OpenStack, and the entity shipping this is the Cloud SIG, where other people participate as well, not limited to RDO itself.

As an example, the qemu-kvm-ev shipped by virt sig, curated by the ovirt project is shipped as the qemu-kvm-ev release, not an ovirt branded component.

Some of the changes you are proposing would make sense if the RDO project would use the CentOS build and release mechanics as the exclusive channels, but that is no currently the case ( eg. https://www.rdoproject.org/Quickstart talks about an rdo-release ). Is the wider goal to have rdoproject abandon their own release process in favour of a CentOS hosted one ?

**Comment by apevec** [comment]
> where is the larger conversation taking place around this

It was yesterday on RDO IRC channel

> Is the wider goal to have rdoproject abandon their own release process in favour of a CentOS hosted one ?

Yes, RDO >= Liberty will be delivered only via CentOS Cloud SIG repo.

More details of the plan in https://trello.com/c/wzdl1IlZ/52-openstack-in-fedora there are links to the rdo-list threads with the summary.

**Comment by apevec** [comment]
> Key things to note here is that the payload we ship is still branded RDO, but is in effect OpenStack

That's why I kept "RDO-OpenStack" in repo labels. RDO project is about packaging OpenStack in RPMs for Red Hat family of distros, using CentOS provided buildsystem and repository infrastructure, but there are other resources (website, ask, IRC, list) outside CentOS.

> and the entity shipping this is the Cloud SIG, where other people participate as well, not limited to RDO itself.

Other people work on other Cloud infra projects, I'm not aware of anyone working on OpenStack RPMs and not working with RDO?

**Comment by apevec** [comment]
Forgot to ping @rbowen as RDO community manager - branding questions for you ^

**Comment by apevec** [comment]
New scratch build for testing http://cbs.centos.org/kojifiles/work/tasks/967/50967/centos-release-rdo-liberty-1-4.el7.noarch.rpm

**Comment by kbsingh** [comment]
adding layers of complexity or messaging isnt ever going to help with the wider picture, or the message we deliver outbound to the userbase. 'centos-release-rdo-liberty' is about the same level of communication as 'centos-release-yewDKhc98s-g9IMbi9yot' for someone who isnt aware of what Liberty is and someone who isn't already engaged with the RDO project.

This is likely worth having a wider conversation on, I'd like to see someone quantify what the concerns are and where this fear comes from.

**Comment by pmyers** [comment]
@kbsingh, this was something I brought up on #rdo yesterday. My rationale for it is the following...

A lot of effort goes into making RDO, from packaging to CI to Delorean and to shepherding the packages through the CentOS build system for them to show up in the CloudSIG repositories. I think it's important that it's clear that what is in that CloudSIG is not 'upstream OpenStack taken from git and packaged for CentOS', because that completely marginalizes the massive effort that the RDO team undertakes. Using a release package like centos-release-openstack-liberty both associates the release specifically with CentOS (when RDO is about availability on all Enterprise Linux derivatives) as well as disassociates it from the RDO community effort.

I (and @markmc) also think it's important that there is a distribution mechanism for RDO that is available from the RDO site itself and not solely through the CentOS CloudSIG. If we had this RDO distribution mechanism for the official (i.e. non-Delorean) releases of RDO OpenStack, then I would be less concerned about the branding of the release package in the CloudSIG.

All that being said, there are better battles to fight, so if you and others feel strongly about this, I won't put up any additional resistance. I just felt like I needed to convey here what was said on irc yesterday, so that you knew why @apevec started this review in the first place.

**Comment by rbowen** [comment]
+1 to Perry's sentiment here, and sorry that my travels have delayed my response. The folks that work on RDO are putting a huge amount of work into this, and recognition is deserved.

**Comment by apevec** [comment]
> 'centos-release-rdo-liberty' is about the same level of communication as 'centos-release-yewDKhc98s-g9IMbi9yot' 

BTW I did keep compat provide centos-release-openstack-liberty.
We needed to include "liberty" version into release RPM name so that existing users on previous Kilo version do not get upgraded by accident.

>  RDO that is available from the RDO site itself and not solely through the CentOS CloudSIG

We had that until Liberty and it's just pain and confusing to keep in sync hence I wanted to consolidate this part of infra using well established CentOS mirroring system on top of buildsystem and CI systems. Redoing all that just for RDO seemed like wasting resources to me.
Anyway, to workaround branding discussion, I'll create rdo-release-liberty RPM on rdoproject.org pointing to SIG repos for RDO >= Liberty while keeping centos-release-openstack-liberty as is.

**Comment by kbsingh** [comment]
@pmyers thanks for the qualification - that helps, and I agree with the sentiment. 

Lets try and see how best we can communicate this through - most of the effort is clearly visible, we just need to get better at exposing it to the wider audience and promoting it. Couple of baseline things we should start with is document up wiki.centos.org/Cloud/OpenStack - and get some of the RDO specific content in there, also for the announcements into each media, we should promote the idea of what is RDO and what that means in these quantified terms.

W.r.t the centos-release file rename, let me think about it and get back within the next day or so;

**Comment by apevec** [comment]
https://repos.fedorapeople.org/repos/openstack/openstack-liberty/rdo-release-liberty.rpm is in place now, using cloud sig repos behind the scene

Also available via redirect: http://rdoproject.org/repos/openstack-liberty/rdo-release-liberty.rpm
in case we move out of FPO site.

**Pull request closed without merging**
